### PR TITLE
Workflow Pt. 2

### PR DESCRIPTION
**Pull request by BD103**
- Linter
- Actions workflow
- Contributing.md

### CODE REVIEW

**Review by JBYT27 — APPROVED** [review]
Approving

**Review by JBYT27 — APPROVED** [review]
Approving

**Comment by JBYT27** [comment]
@BD103, By the way, lint failed

**Review by JBYT27 — APPROVED** [review]
Approving

**Comment by BD103** [comment]
Hey @JBYT27 do you think you could add Github Actions support for Poetry?

**Comment by JBYT27** [comment]
Sure @BD103, though could you explain to me about the poetry development and adding the github actions?
I'm kinda stuck on that :/
Sorry! And thanks!

**Comment by darkdarcool** [comment]
@JBYT27, maybe he means like updating all of the packages? Or running it? But the last one doesn't make sense because when you run python it's automatically installed

**Comment by JBYT27** [comment]
Ok, so you want me to fix that or try something new?

**Comment by BD103** [comment]
Not sure, maybe we'll just put this on the back burner for now.

**Comment by JBYT27** [comment]
Ok

**Pull request merged**
