### PR TITLE
Various Workflow Adjustments

### PR DESCRIPTION
**Pull request by BD103**
WIP

- Revert back to Poetry

### CODE REVIEW

**Review by JBYT27 — APPROVED** [review]
Approving

**Comment by JBYT27** [comment]
@BD103, should I merge?

**Comment by RayhanADev** [comment]
@JBYT27 you're able to merge it I don't see why not :>?

**Comment by JBYT27** [comment]
@RayhanADev, lol ok, I will :D

**Comment by BD103** [comment]
Bruh I'm not done

**Comment by JBYT27** [comment]
@BD103 - lol, ok, sorry

**Pull request merged**
